############# English navigation ##############

# main menu
[[main]]
weight = 1
url = ""
name = "Home"
  
[[main]]
weight = 3
url = "about/"
name = "About"

[[main]]
weight = 2
url = "#"
name = "Subjects"
hasChildren = true

  [[main]]
  parent = "Subjects"
  weight = 1
  url = "tags/"
  name = "Topics"
  
  [[main]]
  parent = "Subjects"
  weight = 2
  url = "categories/"
  name = "Themes"
  
[[main]]
weight = 4
url = "events/"
name = "Upcoming Events"
############################# Footer Menu ########################
[[footer]]
weight = 1
url = "about/"
name = "About"

[[footer]]
weight = 4
url = "categories/"
name = "Themes"

[[footer]]
weight = 3
url = "privacy/"
name = "Privacy"

[[footer]]
weight = 4
url = "terms-conditions/"
name = "Terms & Conditions"